<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(AppTargetFramework)</TargetFrameworks>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>

        <UserSecretsId>04b844dd-6bc6-42c0-b93d-f5cf4e228af4</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="appsettings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="$(TestSdk)" />
        <PackageReference Include="xunit" Version="$(XUnitVersion)" />
        <PackageReference Include="xunit.runner.visualstudio" Version="$(XUnitRunnerVersion)">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="coverlet.collector" Version="6.*">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Localization" Version="$(MicrosoftExtensionsVersion)" />
        <PackageReference Include="Microsoft.Extensions.Logging.Configuration" Version="$(MicrosoftExtensionsVersion)" />
        <PackageReference Include="FluentAssertions" Version="6.*" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Juice.EventBus.RabbitMQ" Version="$(JuiceVersion)" />
        <PackageReference Include="Juice.MediatR" Version="$(JuiceVersion)" />
        <PackageReference Include="Juice.MediatR.Behaviors" Version="$(JuiceVersion)" />
        <PackageReference Include="Juice.Messaging.Idempotency.Redis" Version="$(JuiceVersion)" />
        <PackageReference Include="Juice.Messaging.Outbox.Delivery" Version="$(JuiceVersion)" />
        <PackageReference Include="Juice.Messaging.Outbox.Migrations.SqlServer" Version="$(JuiceVersion)" />
        <PackageReference Include="Juice.Messaging.Outbox.Migrations.PostgreSQL" Version="$(JuiceVersion)" />
        <PackageReference Include="Juice.XUnit" Version="$(JuiceVersion)" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Juice.Timers.Api\Juice.Timers.Api.csproj" />
        <ProjectReference Include="..\..\src\Juice.Timers.EF.PostgreSQL\Juice.Timers.EF.PostgreSQL.csproj" />
        <ProjectReference Include="..\..\src\Juice.Timers.EF.SqlServer\Juice.Timers.EF.SqlServer.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Update="appsettings.Development.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>


</Project>
